name: Create theme release

on:
    release:
        types: [published, edited]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Zip Folder
              run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/**" "*.pcss" "*.asset.php" "node_modules/**" "assets/bundle/css/**/*.js" "src/**" "vendor/**" "vendor-wpcs-php8-bugfix/**" "zip/**" "*.env" ".eslintrc.json" "composer.*" "package*.json" "yarn-*.log" "yarn*.lock" "*.code-workspace" "webpack.*" "tsconfig.*" "phpcs.xml" "pnpm-lock.yaml" "postcss.config.js" "*.zip" ".git/*" ".github/*" "phpcs.xml" "composer.json" "composer.lock" ".gitignore" "node_modules" "package-lock.json" "inc/settings/src"

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ${{ github.event.repository.name }}.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
